### ISSUE TITLE
webSocket.upgradeReq is null in 'connection' event listener in 0.14.1

### ISSUE THREAD

**Issue by taronpa** [uWebSockets/bindings#16]
I have such code

```javascript
const server = require('http').createServer();
const WebSocketServer = require('uws').Server;
const wss = new WebSocketServer({ server: server });

wss.on('connection', (ws) => {
    //prints null
    console.log(ws.upgradeReq);
});

server.listen(3000, () => {
    console.log(`Listening on  ${server.address()}`);
});
```

Everything worked good in uws@0.9.0.
But now I have updated to uws@0.14.1 and upgradeReq is always null in connection payload.

**Comment by alexhultman** [comment]
ws.upgradeReq is only valid in the connection handler and is set to null when it returns. If you check the code you sent here you can see that it is not null.

**Comment by taronpa** [comment]
Thanks a lot. I have simplified my code.

It was 

```javascript
wss.on('connection', (ws) => {
    process.nextTick(() => {
        //prints null
        console.log(ws.upgradeReq);
    });
});
```

So, yeah you assign upgradeReq null before I had print that. So I have changed my code in order to hold  upgradeReq in some other variable.

Sorry for inconvenience.

**Comment by alexhultman** [comment]
Yep exactly. You can easily pick the data you want to keep. The upgradeReq is pretty big (multiple hundreds of mb when having many connections) so I prefer to remove it. I think it would be a much better design to pass upgradeReq as an argument to the handler instead of attaching it to the socket. Most users only use upgradeReq in the connection handler. So this is a balance between being compatible with ws and having good memory usage.
